// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcggkatzphmusuzoaoed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZ2drYXR6cGhtdXN1em9hb2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTI3NzYsImV4cCI6MjA2MzU4ODc3Nn0.774uRLDjEc4MFsE38UcWHpWsn8MlIRX1GDoTsNakicY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);